apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: finup
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host: wenzhen-finup.mobvoi.com
    http:
      paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 8717
