---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: kube-ops
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - name: web
    port: 8080
    nodePort: 31000
    targetPort: web
  - name: agent
    port: 50000
    nodePort: 31001
    targetPort: agent
