apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops1-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 10.19.255.192
    path: /ufs-5zof3d5v/devops1/jenkins
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devops1-pvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
