---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jenkins
  name: opspv1
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  cephfs:
    monitors:
      - '10.1.204.105:6789'
      - '10.1.204.106:6789'
      - '10.1.204.107:6789'
    path: jenkins
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opspvc1
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
